### ISSUE TITLE
deploy local dir blows up on Windows

### ISSUE THREAD

**Issue by friism** [heroku/heroku-build#3]
```
C:\Users\IEUser\.heroku\node_modules\heroku-builds\node_modules\heroku-client\node_modules\q\q.js:126
                    throw e;
                          ^
Error: Expected response to be successful, got 400
    at Request.handleFailure (C:\Users\IEUser\.heroku\node_modules\heroku-builds
\node_modules\heroku-client\lib\request.js:258:9)
    at ConcatStream.directResponse [as cb] (C:\Users\IEUser\.heroku\node_modules
\heroku-builds\node_modules\heroku-client\lib\request.js:167:12)
    at ConcatStream.end (C:\Users\IEUser\.heroku\node_modules\heroku-builds\node
_modules\heroku-client\node_modules\concat-stream\index.js:44:21)
    at IncomingMessage.onend (_stream_readable.js:489:10)
    at IncomingMessage.g (events.js:257:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:349:13)

C:\Users\IEUser\Documents\Visual Studio 2015\Projects\node-js-sample>
```

**Comment by friism** [comment]
Fixes
